config/routes.rb
MediaBrowser::Application.routes.draw do

  match '/about', :to   => 'pages#about'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis
  def title
    base_title = "Media Browser"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    !cookies[:vk_app_2728031].nil?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    <%= javascript_include_tag 'http://vkontakte.ru/js/api/openapi.js' %>
    <%= javascript_include_tag 'jquery-1.7.1.min' %>
    <%= javascript_include_tag 'imtech_pager' %>
  </head>
  <body>
  <%= javascript_include_tag 'custom' %>
    <div class="container">
      <section class="main round">
        <%= yield %>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
          </ul>
        </nav>
      </section>
    </div>
  </body>
</html>
</html>

app/views/pages/_home_not_signed_in.html.erb
<div class="header1">Media Browser</div>
<div class="header2"> VKontakte </div>
<div class="img1">
  <%= image_tag("logo1.png", :class => "round") %>
</div>
<div class="img2">
  <%= image_tag("logo2.png", :class => "round") %>
</div>
<div id="login_button" onclick="VK.Auth.login(authInfo, 8216);"></div>

<script language="javascript">

  function authInfo(response) {
    if (response.session) {
      window.location.reload();
    }
  }
  VK.UI.button('login_button');

</script>

app/views/pages/_home_signed_in.html.erb
<div class="logout">
  <a href="#" onclick="VK.Auth.logout(authInfo);">Logout</a>
</div>

<header>
  <div><%= image_tag("logo1.png", :class => "logo") %></div>
  <h1>Media Browser</h1>
</header>

<section class="profile">
  <img src=""/>
  <h7></h7>
  <h5>News</h5>
  <section class="news">
  </section>
</section>

<section class="media">
  <div id="content"></div>
  <div id="pagingControls"></div>
</section>

<script type="text/javascript">
  // Initialize pager
  var pager = new Imtech.Pager();

  // Get Login Status
  VK.Auth.getLoginStatus(getProfileInfo);

  function getProfileInfo(s) {

    if (s.session) {

	  // Get Profile Info
	  VK.Api.call('getProfiles', { uids: s.session.mid, 
	                               fields: 'first_name, last_name, photo_medium, bdate' }, 
	                               function(r) {
		  if (r.response) {
		      $("section.profile > img").attr('src', r.response[0].photo_medium);
		      $("section.profile > h7").html(r.response[0].first_name + 
		                                     ' ' + 
		                                     r.response[0].last_name +
		                                     ', ' +
		                                     getAge(r.response[0].bdate));
	      }
	    });
      }
  };

  // Get Newsfeed
  VK.Api.call('newsfeed.get', { count: 4, filters: 'post' }, function(r) {
    if (r.response) {
      for (var key in r.response.items) {
        if (r.response.items[key].text) {
          $("section.news").append(
            '<div class="news_entry">' +
            limitText(r.response.items[key].text, 50) +
            '</div>'
          );
        }
      }
    }
  });

  // Get Audio Files
  VK.Api.call('audio.get', {}, function(r) {
    if (r.response) {
      for (var key in r.response) {
        $("div#content").append(
          '<div class="media_entry">' +
          '<a href="' + r.response[key].url + '"><img src="images/download.png" /></a>' +
          '<a href="#" class="play"><img src="images/listen.png" /></a>' +
          '<div class="artist">' +
          limitText(r.response[key].artist, 25) + 
          '</div>' +
          '-' +
          '<div class="name">' + 
          limitText(r.response[key].title, 25) +
          '</div>' +
          '<audio preload="none"><source src="' + r.response[key].url + '" type="audio/mp3" /></audio>' +
          '</div>');
      }
      
      // Init Pager
      pager.paragraphsPerPage = 13; // set amount elements per page
      pager.pagingContainer = $('#content'); // set of main container
      pager.paragraphs = $('div.media_entry', pager.pagingContainer); // set of required containers
      pager.showPage(1);
    }
  });
  
  // Init Audio Play Handler
  $('a.play').live('click', function() {
    var audio = $(this).parent().children('audio').get(0);
    if (audio.paused) {
      audio.play();
      $(this).children('img').attr('src', 'images/pause.png');
    } else {
      audio.pause();
      $(this).children('img').attr('src', 'images/listen.png');
    }
  });

</script>

<script language="javascript">

  function authInfo(response) {
    window.location.reload();
  }

</script>

app/views/pages/about.html.erb
<section class="about">
  The single purpose of this project is to demo VKontakte OpenAPI.
This is not meant for final users to download media content from VK site
without VK permission.
</section>

app/views/pages/home.html.erb
<% if signed_in? %>
  <%= render 'home_signed_in' %>
<% else %>
  <%= render 'home_not_signed_in' %>
<% end %>